### ISSUE TITLE
Code Does Not Apply Dark Mode on Paste

### ISSUE THREAD

**Issue by Shubham18024** [FireHead90544/PWUtils#3]
Hello,

I found an issue with the dark mode script. When pasting the code into the console, it doesn't immediately change the theme to dark mode. The current implementation only sets up keyboard shortcuts, which means the user has to manually trigger the theme change.

Steps to Reproduce:

Copy the script to the clipboard.
Paste it into the console on the Physics Wallah website.
I Notice that the theme does not change immediately.

**Comment by FireHead90544** [comment]
Fixed in PR #4
